name: utility
description: Utility helps JS and TS developers to use dart more efficiently with use of utility.
version: 1.0.0
homepage: https://www.kawal.dev

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
