name: utility
description: Utility helps Java-Script and Type-Script developers to migrate to dart and use it more effeciently.
version: 1.0.0
homepage: https://www.kawal.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
