name: utility
description: Utility helps JS and TS developers to use dart more efficiently with use of utility.
version: 1.0.0
homepage: https://www.kawal.dev

environment:
  sdk: '>=2.9.3 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
